name: 'Jarvis action status report action'
description: 'Send action status telegram message'
inputs:
  report_to:
    description: 'Chat to report'
    required: true
  token:
    description: 'Telegram token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: beacon-biosignals/job-context@v1
      id: job-data
    - name: Jarvis send report
      uses: appleboy/telegram-action@v1.0.0
      if: success() || failure()
      with:
        to: ${{ inputs.report_to }}
        token: ${{ inputs.token }}
        disable_notification: ${{ job.status == 'success' && true || false }}
        format: markdown
        disable_web_page_preview: true
        message: |
          ${{ job.status == 'success' && '🟢' || '🔴' }} *CI/CD:* [${{ job.status == 'success' && 'SUCCESS' || 'FAILURE' }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{ steps.job-data.outputs.id }}) *${{ github.workflow }}:${{ github.job }}* workflow, triggered by: _${{ github.actor }}_
          Branch: `${{ github.ref_name }}`, Repository: `${{ github.repository }}`
